export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  safelist: [
    'text-spec-info',
    'text-spec-danger',
    'text-spec-warning',
    'text-spec-accent',
    'text-red-400',
    'text-orange-400',
    'text-yellow-400',
    'text-blue-400',
    'text-green-400',
    'text-red-500',
    'text-orange-500',
    'text-yellow-500',
    'text-blue-500',
    'text-green-500',
    'bg-red-500/10',
    'bg-orange-500/10',
    'bg-yellow-500/10',
    'bg-blue-500/10',
    'bg-green-500/10',
    'border-red-500/50',
    'border-orange-500/50',
    'border-yellow-500/50',
    'border-blue-500/50',
    'border-green-500/50',
    'bg-red-500/20',
    'bg-orange-500/20',
    'bg-yellow-500/20',
  ],
  theme: {
    extend: {
      colors: {
        'spec-bg': '#0f0f0f',
        'spec-surface': '#1a1a1a',
        'spec-card': '#252525',
        'spec-border': '#3a3a3a',
        'spec-accent': '#ff2a2a',
        'spec-accent-light': '#ff6b6b',
        'spec-danger': '#ff0055',
        'spec-warning': '#ffaa00',
        'spec-info': '#00aaff',
      },
      fontFamily: {
        serif: ['Instrument Serif', 'serif'],
        mono: ['DM Mono', 'Geist Mono', 'monospace'],
        sans: ['Stack Sans Notch', 'Geist', 'sans-serif'],
      },
      boxShadow: {
        'glow-accent': '0 0 20px rgba(255, 42, 42, 0.3)',
        'glow-lg': '0 0 30px rgba(255, 42, 42, 0.4)',
      },
      keyframes: {
        'logo-gradient': {
          '0%': { backgroundPosition: '0%' },
          '100%': { backgroundPosition: '300%' },
        },
      },
      animation: {
        'logo-gradient': 'logo-gradient 2.8s linear infinite',
      },
    },
  },
  plugins: [],
};